### ISSUE TITLE
Slight Error in Readme?

### ISSUE THREAD

**Issue by ToluClassics** [guillaume-be/rust-tokenizers#96]
Hi @guillaume-be , Thank you for this awesome library

I believe the line from the readme ==> 

```rust
let vocab = Arc::new(rust_tokenizers::BertVocab::from_file(&vocab_path));
let bert_tokenizer: BertTokenizer = BertTokenizer::from_existing_vocab(vocab.clone());
```

should be

```rust
let strip_accents = false;
let lower_case = false;
let vocab = rust_tokenizers::vocab::BertVocab::from_file(&vocab_path);
let bert_tokenizer: BertTokenizer =
        BertTokenizer::from_existing_vocab(vocab, lower_case, strip_accents);
```

If this is the case, I can send a PR to fix

**Comment by guillaume-be** [comment]
Hello @ToluClassics,

You are right - the API changed a few version back and the readme was not updated. It would be great if you could send a PR to fix the README (and other documentation referring to this older API). 

Thank you!

**Comment by guillaume-be** [comment]
Fixed in https://github.com/guillaume-be/rust-tokenizers/pull/97
